import{randomUUID}from"node:crypto";import{z}from"zod";import{getDb}from"@/lib/db";import{AppError}from"@/lib/errors";import type{SessionUser}from"@/server/auth";import{audit}from"@/server/audit";import{caseStatuses,getCaseForActor,listCasesForActor}from"@/server/cases";
export interface UserOption{id:string;email:string;displayName:string;role:string}export interface ReviewNoteRow{id:string;caseId:string;reviewerId:string;note:string;flags:string[];createdAt:string}
const reviewSchema=z.object({note:z.string().trim().min(2).max(2000),flags:z.array(z.enum(["DUPLICATE_MATERIAL","FACT_CONFLICT","MATERIAL_GAP","NON_FACTUAL_WORDING"])).max(10)});
export function listReviewers(admin:SessionUser):UserOption[]{if(admin.role!=="ADMIN")throw new AppError("FORBIDDEN","仅管理员可查看复核员列表",403);return getDb().prepare("SELECT id,email,display_name AS displayName,role FROM users WHERE role='REVIEWER' ORDER BY display_name").all()as unknown as UserOption[];}
export function assignReviewer(admin:SessionUser,caseId:string,reviewerId:string):void{if(admin.role!=="ADMIN")throw new AppError("FORBIDDEN","仅管理员可分配复核员",403);getCaseForActor(admin,caseId);const reviewer=getDb().prepare("SELECT id FROM users WHERE id=? AND role='REVIEWER'").get(reviewerId);if(!reviewer)throw new AppError("INVALID_REVIEWER","复核员不存在",400);getDb().prepare("UPDATE cases SET assigned_reviewer_id=?,status='PENDING_MANUAL_REVIEW',updated_at=? WHERE id=?").run(reviewerId,new Date().toISOString(),caseId);audit(admin,"REVIEWER_ASSIGNED","CASE",caseId,"SUCCESS",{reviewerId});}
export function addReviewNote(actor:SessionUser,caseId:string,raw:unknown):ReviewNoteRow{const input=reviewSchema.parse(raw);const item=getCaseForActor(actor,caseId);if(actor.role!=="ADMIN"&&(actor.role!=="REVIEWER"||item.assignedReviewerId!==actor.id))throw new AppError("FORBIDDEN","只能复核分配给自己的案件",403);const id=randomUUID();getDb().prepare("INSERT INTO review_notes(id,case_id,reviewer_id,note,flags_json,created_at)VALUES(?,?,?,?,?,?)").run(id,caseId,actor.id,input.note,JSON.stringify(input.flags),new Date().toISOString());audit(actor,"REVIEW_NOTE_ADDED","CASE",caseId,"SUCCESS",{flagCount:input.flags.length});return listReviewNotes(actor,caseId).find(x=>x.id===id)!;}
export function listReviewNotes(actor:SessionUser,caseId:string):ReviewNoteRow[]{getCaseForActor(actor,caseId);return(getDb().prepare("SELECT id,case_id AS caseId,reviewer_id AS reviewerId,note,flags_json AS flagsJson,created_at AS createdAt FROM review_notes WHERE case_id=? ORDER BY created_at DESC").all(caseId)as Array<Omit<ReviewNoteRow,"flags">&{flagsJson:string}>).map(x=>({...x,flags:JSON.parse(x.flagsJson)as string[]}));}
export function updateCaseStatus(actor:SessionUser,caseId:string,status:string):void{const parsed=z.enum(caseStatuses).parse(status);const item=getCaseForActor(actor,caseId);if(actor.role==="USER"||actor.role==="REVIEWER"&&item.assignedReviewerId!==actor.id)throw new AppError("FORBIDDEN","无权更新后台状态",403);const reviewerAllowed=["WAITING_MORE_MATERIALS","COMPLETED","PENDING_MANUAL_REVIEW"];if(actor.role==="REVIEWER"&&!reviewerAllowed.includes(parsed))throw new AppError("FORBIDDEN","复核员不能设置该状态",403);getDb().prepare("UPDATE cases SET status=?,updated_at=? WHERE id=?").run(parsed,new Date().toISOString(),caseId);audit(actor,"CASE_STATUS_UPDATED","CASE",caseId,"SUCCESS",{status:parsed});}
export function getSystemSummary(admin:SessionUser){if(admin.role!=="ADMIN")throw new AppError("FORBIDDEN","仅管理员可查看系统状态",403);const one=(sql:string)=>(getDb().prepare(sql).get()as{count:number}).count;return{users:one("SELECT COUNT(*) AS count FROM users"),cases:one("SELECT COUNT(*) AS count FROM cases"),evidence:one("SELECT COUNT(*) AS count FROM evidence"),pendingReview:one("SELECT COUNT(*) AS count FROM cases WHERE status='PENDING_MANUAL_REVIEW'"),storageMode:"private-local-test-only",extractionProvider:"mock"};}
export function listAuditLogs(admin:SessionUser,limit=100){if(admin.role!=="ADMIN")throw new AppError("FORBIDDEN","仅管理员可查看审计日志",403);return getDb().prepare("SELECT id,actor_id AS actorId,actor_role AS actorRole,action,resource_type AS resourceType,resource_id AS resourceId,outcome,metadata_json AS metadataJson,created_at AS createdAt FROM audit_logs ORDER BY created_at DESC LIMIT ?").all(Math.min(limit,200));}
export function reviewerQueue(actor:SessionUser){if(actor.role!=="REVIEWER"&&actor.role!=="ADMIN")throw new AppError("FORBIDDEN","无后台访问权限",403);return listCasesForActor(actor);}

