import { readFile } from "node:fs/promises";
import { getDb, withTransaction } from "@/lib/db";
import { AppError } from "@/lib/errors";
import { assertDemoMode, DEMO_CASE_TITLE, DEMO_TEMPLATE_KEY, demoAssetPath, demoAssets, type DemoAsset } from "@/lib/demo";
import type { SessionUser } from "@/server/auth";
import { createCase, getCaseForActor, listCasesForActor, type CaseRow } from "@/server/cases";
import { deleteCaseData } from "@/server/deletion";
import { extractCase, listExtractions } from "@/server/extraction";
import { deleteEvidence, listEvidence, storeEvidence, validateUpload, type EvidenceRow } from "@/server/storage";

interface PreparedAsset { asset:DemoAsset;bytes:Buffer }
export interface DemoProvisionDependencies { readAsset?:(asset:DemoAsset)=>Promise<Buffer>;store?:typeof storeEvidence;extract?:typeof extractCase;afterCaseCreated?:()=>void }

function requireDemoUser(actor:SessionUser):void{assertDemoMode();if(actor.role!=="USER")throw new AppError("FORBIDDEN","演示案件仅供普通用户测试",403);}
function assertDemoSchema():void{try{const columns=new Set((getDb().prepare("PRAGMA table_info(cases)").all()as{name:string}[]).map(x=>x.name));for(const required of["is_demo","demo_template_key","demo_setup_state"])if(!columns.has(required))throw new Error(required);}catch{throw new AppError("DATABASE_MIGRATION_REQUIRED","本地数据库尚未完成演示模板迁移，请运行 npm run db:migrate 后重启开发服务。",503);}}
const field=<T extends string|number>(value:T)=>({value,state:"USER_CONFIRMED"as const,evidenceSupport:"USER_STATEMENT"as const,savedAt:new Date().toISOString()});
export function demoCaseInput(){return{title:DEMO_CASE_TITLE,disputeType:"GYM"as const,screening:{eligible:true,reasons:["虚构健身预付服务演示案例"],suggestedMaterials:["付款记录","商家主体信息","至少一份沟通记录","合同与服务使用记录"],safetyNotice:null,boundary:"只整理材料，不提供法律结论。"},details:{merchantLegalName:field("星云健康管理有限公司（虚构）"),storeName:field("星云健身天府店（虚构）"),serviceName:field("健身年卡"),paymentAmountYuan:field(2999),paymentDate:field("2026-05-15"),orderOrContractNumber:field("DEMO-2026-001 / DEMO-CONTRACT-001"),usedAmountOrCount:field("已使用约1个半月"),remainingAmountOrCount:field("仍有剩余服务，具体待核对"),firstRefundRequestDate:field("2026-07-01"),merchantResponse:field("已办理年卡原则上不予退费"),desiredResolution:field("退还未消费部分费用")}};}

async function prepareAssets(readAsset:(asset:DemoAsset)=>Promise<Buffer>):Promise<PreparedAsset[]>{const prepared:PreparedAsset[]=[];for(const asset of demoAssets){let bytes:Buffer;try{bytes=await readAsset(asset);}catch{throw new AppError("DEMO_ASSET_MISSING",`演示资料“${asset.fileName}”尚未初始化，请运行 npm run demo:generate-assets。`,503,{assetId:asset.id});}try{validateUpload(new File([new Uint8Array(bytes)],asset.fileName,{type:asset.mimeType}),bytes);}catch(error){if(error instanceof AppError)throw new AppError("DEMO_ASSET_INVALID",`演示资料“${asset.fileName}”未通过上传校验，请重新生成演示资料。`,503,{assetId:asset.id,validationCode:error.code});throw error;}prepared.push({asset,bytes});}return prepared;}
export function getMyDemoCase(actor:SessionUser):CaseRow|undefined{requireDemoUser(actor);assertDemoSchema();return listCasesForActor(actor).find(item=>item.demoTemplateKey===DEMO_TEMPLATE_KEY);}
function isComplete(actor:SessionUser,item:CaseRow):boolean{return item.demoSetupState==="READY"&&listEvidence(actor,item.id).length===demoAssets.length&&listExtractions(actor,item.id).length>0;}

async function cleanupFailedCase(actor:SessionUser,caseId:string):Promise<void>{try{await deleteCaseData(actor,caseId);}catch{try{getDb().prepare("UPDATE cases SET demo_setup_state='FAILED' WHERE id=? AND owner_id=?").run(caseId,actor.id);}catch{/* doctor will report migration/storage failure */}}}
export async function createOrRestoreDemoCase(actor:SessionUser,deps:DemoProvisionDependencies={}):Promise<CaseRow>{
  requireDemoUser(actor);assertDemoSchema();const readAsset=deps.readAsset??(asset=>readFile(demoAssetPath(asset.fileName)));const prepared=await prepareAssets(readAsset);let existing=getMyDemoCase(actor);
  if(existing&&isComplete(actor,existing))return existing;
  if(existing){await deleteCaseData(actor,existing.id);existing=undefined;}
  let created:CaseRow|undefined;
  try{created=createCase(actor,demoCaseInput());withTransaction(db=>db.prepare("UPDATE cases SET is_demo=1,demo_template_key=?,demo_setup_state='INITIALIZING' WHERE id=? AND owner_id=?").run(DEMO_TEMPLATE_KEY,created!.id,actor.id));deps.afterCaseCreated?.();const store=deps.store??storeEvidence;for(const{asset,bytes}of prepared)await store(actor,created.id,new File([new Uint8Array(bytes)],asset.fileName,{type:asset.mimeType}),asset.category);await(deps.extract??extractCase)(actor,created.id);getDb().prepare("UPDATE cases SET demo_setup_state='READY' WHERE id=? AND owner_id=?").run(created.id,actor.id);return getCaseForActor(actor,created.id);}catch(error){if(created)await cleanupFailedCase(actor,created.id);if(error instanceof AppError)throw error;const message=error instanceof Error?error.message:"unknown";if(/UNIQUE|constraint/i.test(message))throw new AppError("DEMO_CASE_CONFLICT","你的演示案件已由另一次请求创建，请重试以打开已有案件。",409);if(/storage|file|directory|EPERM|EACCES|ENOSPC/i.test(message))throw new AppError("STORAGE_UNAVAILABLE","本地私有存储暂不可用，请检查目录权限后重试。",503);throw new AppError("DEMO_SEED_FAILED","演示案件初始化失败，本次创建内容已清理，可以安全重试。",500,{reason:error instanceof Error?error.name:"unknown"});}
}
export async function resetMyDemoCase(actor:SessionUser,deps:DemoProvisionDependencies={}):Promise<CaseRow>{requireDemoUser(actor);const existing=getMyDemoCase(actor);if(existing)await deleteCaseData(actor,existing.id);return createOrRestoreDemoCase(actor,deps);}
export async function loadDemoEvidence(actor:SessionUser,caseId:string,assetIds:string[]=demoAssets.map(x=>x.id)):Promise<EvidenceRow[]>{requireDemoUser(actor);assertDemoSchema();const item=getCaseForActor(actor,caseId);if(!item.isDemo||item.ownerId!==actor.id)throw new AppError("NOT_DEMO_CASE","只能向自己的演示案件载入演示材料",403);const selected=demoAssets.filter(asset=>assetIds.includes(asset.id));if(!selected.length)throw new AppError("NO_DEMO_ASSET","请选择至少一份演示材料",400);const prepared=await prepareAssets(asset=>readFile(demoAssetPath(asset.fileName)));const byId=new Map(prepared.map(x=>[x.asset.id,x]));const existing=new Set(listEvidence(actor,caseId).map(x=>x.originalName));for(const asset of selected){if(existing.has(asset.fileName))continue;const preparedAsset=byId.get(asset.id)!;try{await storeEvidence(actor,caseId,new File([new Uint8Array(preparedAsset.bytes)],asset.fileName,{type:asset.mimeType}),asset.category);}catch(error){if(error instanceof AppError)throw error;throw new AppError("STORAGE_UNAVAILABLE","本地私有存储暂不可用，请检查目录权限后重试。",503);}}return listEvidence(actor,caseId);}
export async function clearDemoEvidence(actor:SessionUser,caseId:string):Promise<void>{requireDemoUser(actor);assertDemoSchema();const item=getCaseForActor(actor,caseId);if(!item.isDemo||item.ownerId!==actor.id)throw new AppError("NOT_DEMO_CASE","只能清空自己的演示案件材料",403);for(const file of listEvidence(actor,caseId))await deleteEvidence(actor,file.id);getDb().prepare("UPDATE cases SET demo_setup_state='PARTIAL' WHERE id=?").run(caseId);}
