import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { access, rm } from "node:fs/promises";
import { join } from "node:path";
import { closeDb, getDb, migrate } from "@/lib/db";
import { evaluateScreening } from "@/lib/screening";
import type { SessionUser } from "@/server/auth";
import { createCase } from "@/server/cases";
import { confirmExtraction, extractCase } from "@/server/extraction";
import { storeEvidence } from "@/server/storage";
import { confirmTimeline, generateTimeline } from "@/server/timeline";
import { generateMatrix } from "@/server/matrix";
import { buildMaterials } from "@/server/materials";
import { generateExports } from "@/server/export";
import { activateTestOrder, requestTestPlan } from "@/server/plans";
import { addReviewNote, assignReviewer } from "@/server/backoffice";
import { deleteCaseData } from "@/server/deletion";

const owner:SessionUser={id:"e2e-owner",email:"owner@e2e.local",displayName:"虚构消费者",role:"USER"};const reviewer:SessionUser={id:"e2e-reviewer",email:"reviewer@e2e.local",displayName:"虚构复核员",role:"REVIEWER"};const admin:SessionUser={id:"e2e-admin",email:"admin@e2e.local",displayName:"虚构管理员",role:"ADMIN"};
beforeAll(()=>{closeDb();migrate();const db=getDb();for(const user of[owner,reviewer,admin])db.prepare("INSERT INTO users(id,email,display_name,role,password_hash,created_at)VALUES(?,?,?,?,?,?)").run(user.id,user.email,user.displayName,user.role,"x",new Date().toISOString());db.prepare("INSERT INTO plans(id,code,name,description,limitations,active)VALUES('e2e-plan','HUMAN_REVIEW','人工复核版','测试交付','不保证结果',1)").run();});
afterAll(async()=>{closeDb();await Promise.all([rm(".data/test-storage",{recursive:true,force:true}),rm(".data/test-generated",{recursive:true,force:true})])});
describe("虚构健身年卡完整工作流",()=>{it("从预筛走到复核、交付和完整删除",async()=>{const field=<T>(value:T,state:"CONFIRMED"|"PENDING"="CONFIRMED")=>({value,state});const screening=evaluateScreening({disputeType:"GYM",amountYuan:2999,isConsumerService:true,merchantOperating:"YES",hasPaymentRecord:true,hasContractOrChat:true,desiredOutcome:"整理材料并继续协商退费",hasNegotiated:true,excludedArea:"NONE"});expect(screening.eligible).toBe(true);const item=createCase(owner,{title:"星云健身年卡退费（完整虚构案例）",disputeType:"GYM",screening,details:{merchantLegalName:field("星云健康管理有限公司（虚构）"),storeName:field("星云健身中心（虚构）"),serviceName:field("年度健身服务"),paymentAmountYuan:field(2999),paymentDate:field("2026-01-15"),orderOrContractNumber:field("DEMO-E2E-001"),usedAmountOrCount:field("4 次"),remainingAmountOrCount:field("8 个月","PENDING"),firstRefundRequestDate:field("2026-05-20"),merchantResponse:field("暂不接受退费","PENDING"),desiredResolution:field("整理材料并继续协商退费")}});const payment=await storeEvidence(owner,item.id,new File(["付款记录\n2026年1月15日\n实付 2999 元\n收款方：星云健康管理有限公司（虚构）\n订单号：DEMO-E2E-001"],"虚构付款记录.txt",{type:"text/plain"}),"PAYMENT_ORDER");await storeEvidence(owner,item.id,new File(["服务：年度健身服务\n合同号：DEMO-E2E-001\n剩余次数：8个月"],"虚构服务约定.txt",{type:"text/plain"}),"CONTRACT");await storeEvidence(owner,item.id,new File(["2026年5月20日\n退费请求：请求协商退回未使用部分费用\n商家回复：暂不接受退费"],"虚构退费沟通.txt",{type:"text/plain"}),"REFUND_COMMUNICATION");const extracted=await extractCase(owner,item.id);for(const row of extracted.filter(x=>x.originalValueJson!==null))confirmExtraction(owner,row.id,{action:"CONFIRM"});const timeline=generateTimeline(owner,item.id);expect(timeline.map(x=>x.eventType)).toEqual(expect.arrayContaining(["PAYMENT","REFUND_REQUEST","MERCHANT_RESPONSE"]));expect(timeline.find(x=>x.eventType==="PAYMENT")?.evidenceIds).toContain(payment.id);confirmTimeline(owner,item.id);expect(generateMatrix(owner,item.id)).toHaveLength(timeline.length);const materials=buildMaterials(owner,item.id);expect(materials.disclaimer).toContain("不构成法律意见");expect(materials.drafts.every(x=>x.title.includes("草稿"))).toBe(true);const exports=await generateExports(owner,item.id);expect(exports).toHaveLength(9);const order=requestTestPlan(owner,item.id,"e2e-plan");activateTestOrder(admin,order.id);assignReviewer(admin,item.id,reviewer.id);expect(addReviewNote(reviewer,item.id,{note:"已核对日期、金额和证据回链，建议用户确认剩余服务记录。",flags:["MATERIAL_GAP"]}).flags).toContain("MATERIAL_GAP");const evidencePath=join(".data/test-storage",payment.storageKey);await deleteCaseData(owner,item.id);expect(getDb().prepare("SELECT id FROM cases WHERE id=?").get(item.id)).toBeUndefined();await expect(access(evidencePath)).rejects.toThrow();expect((getDb().prepare("SELECT COUNT(*) AS count FROM audit_logs WHERE action='CASE_DELETED' AND resource_id=?").get(item.id)as{count:number}).count).toBe(1);},30_000);});

