"use client";
/* eslint-disable @next/next/no-img-element -- authenticated private demo thumbnails are intentionally unoptimized */
import { useState } from "react";
import { useRouter } from "next/navigation";
import { demoAssets } from "@/lib/demo";

export function DemoEvidenceTools({caseId}:{caseId:string}){
  const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const router=useRouter();
  async function load(assetIds?:string[]){setBusy(true);setMessage("正在按普通上传规则校验并载入…");const response=await fetch(`/api/demo/cases/${caseId}/evidence`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assetIds})});const data=await response.json();setBusy(false);if(!response.ok)return setMessage(data.error?.message??"载入失败，请重试");setMessage(`已载入 ${data.evidence.length} 份材料；图片/PDF 在 Mock 模式进入人工处理，TXT 可执行结构化提取。`);router.refresh();}
  async function clear(){if(!confirm("清空当前演示案件的全部证据？基础信息不会删除。"))return;setBusy(true);const response=await fetch(`/api/demo/cases/${caseId}/evidence`,{method:"DELETE"});setBusy(false);if(!response.ok)return setMessage("清空失败，请重试");setMessage("演示证据已清空。");router.refresh();}
  async function simulate(){setBusy(true);setMessage("正在调用与普通用户相同的 Mock 提取接口…");const response=await fetch(`/api/cases/${caseId}/extract`,{method:"POST"});const data=await response.json();setBusy(false);if(!response.ok)return setMessage(data.error?.message??"Mock 提取失败，请先载入至少一份材料");router.push(`/cases/${caseId}/extractions`);router.refresh();}
  async function reset(){if(!confirm("只删除并重建你自己的演示案件，其他案件不受影响。继续吗？"))return;setBusy(true);const response=await fetch("/api/demo/cases",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"reset"})});const data=await response.json();setBusy(false);if(!response.ok)return setMessage(data.error?.message??"重置失败，请重试");router.replace(`/cases/${data.case.id}`);router.refresh();}
  return <details className="demo-tools"><summary>演示资料与快捷测试 <span>仅开发测试环境可见</span></summary><p>一键载入和单份载入都调用与手工上传相同的文件校验、摘要去重和私有存储服务。</p><div className="actions"><button type="button" className="button" disabled={busy} onClick={()=>load()}>一键载入全部演示证据</button><button type="button" className="button secondary" disabled={busy} onClick={simulate}>模拟 OCR/Mock 提取完成</button><button type="button" className="button secondary" disabled={busy} onClick={()=>router.push("/screening")}>创建空白案件</button><button type="button" className="button secondary" disabled={busy} onClick={clear}>清空演示证据</button><button type="button" className="button danger" disabled={busy} onClick={reset}>重置当前演示案件</button></div><label>跳转到指定步骤<select defaultValue="" onChange={event=>event.target.value&&router.push(event.target.value)}><option value="" disabled>选择步骤</option><option value={`/cases/${caseId}`}>上传证据</option><option value={`/cases/${caseId}/extractions`}>确认提取结果</option><option value={`/cases/${caseId}/timeline`}>确认时间线</option><option value={`/cases/${caseId}/matrix`}>证据矩阵</option><option value={`/cases/${caseId}/gaps`}>补充材料</option><option value={`/cases/${caseId}/downloads`}>生成和下载</option></select></label><div className="demo-asset-grid">{demoAssets.map(asset=><article className="demo-asset" key={asset.id}>{asset.mimeType==="image/png"?<img src={`/api/demo/assets/${asset.id}`} alt={`${asset.title}虚构示例缩略图`}/>:<div className="asset-placeholder">{asset.mimeType==="application/pdf"?"PDF":"TXT"}</div>}<strong>{asset.fileName}</strong><span>{asset.reason}</span><button type="button" disabled={busy} onClick={()=>load([asset.id])}>载入此材料</button></article>)}</div>{message&&<p className="notice" aria-live="polite">{message}</p>}</details>;
}
