"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";

const messages:Record<string,string>={DEMO_MODE_DISABLED:"演示模式尚未启用。请在本地环境开启 DEMO_MODE_ENABLED 并重启开发服务。",DEMO_ASSET_MISSING:"演示资料尚未初始化，请联系开发者运行 npm run demo:generate-assets。",DEMO_ASSET_INVALID:"演示资料未通过文件校验，请重新生成演示资料。",DATABASE_MIGRATION_REQUIRED:"本地数据库尚未完成演示迁移，请运行 npm run db:migrate 并重启服务。",STORAGE_UNAVAILABLE:"本地私有存储不可写，请检查存储目录权限后重试。",DEMO_CASE_CONFLICT:"你的演示案件已由另一次操作创建，请点击重试打开已有案件。",DEMO_SEED_FAILED:"演示案件初始化失败，本次半成品已清理，可以安全重试。"};
export function DemoCaseActions({existingCaseId}:{existingCaseId?:string}){const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[errorCode,setErrorCode]=useState("");const[lastAction,setLastAction]=useState<"create"|"reset">("create");const router=useRouter();async function act(action:"create"|"reset"){setLastAction(action);setBusy(true);setErrorCode("");setMessage(action==="reset"?"正在只重建你的演示案件…":"正在准备案件、8 份虚构证据和 Mock 提取结果…");try{const response=await fetch("/api/demo/cases",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});const data=await response.json()as{case?:{id:string};error?:{code?:string;message?:string}};if(!response.ok||!data.case){const code=data.error?.code??"INTERNAL_ERROR";setErrorCode(code);setMessage(messages[code]??data.error?.message??"演示案件暂时无法初始化，请根据错误编号检查本地环境。");return;}setMessage(existingCaseId&&action==="create"?"演示案件已存在，正在打开并检查完整性…":"演示案件初始化完成，正在打开…");router.replace(`/cases/${data.case.id}`);router.refresh();}catch{setErrorCode("REQUEST_FAILED");setMessage("无法连接本地开发服务，请确认服务已经重启并再次尝试。演示案件不会重复创建。");}finally{setBusy(false);}}
  return <details className="demo-tools card" open={Boolean(errorCode)}><summary>演示测试工具 <span>仅开发测试环境可见</span></summary><p>所有主体、人物、编号和材料均为虚构。创建操作是幂等的，并执行真实文件校验、权限检查和私有存储流程。</p><div className="actions"><button className="button" disabled={busy} onClick={()=>act("create")}>{busy?"正在初始化完整演示案件…":"使用演示案件体验完整流程"}</button><button className="button secondary" disabled={busy} onClick={()=>router.push("/screening")}>新建空白案件</button>{existingCaseId&&<button className="button danger" disabled={busy} onClick={()=>confirm("只会删除并重建你自己的演示案件，继续吗？")&&act("reset")}>重新创建演示案件</button>}</div>{message&&<div className={errorCode?"notice warning":"notice"} role="status" aria-live="polite"><p>{message}</p>{errorCode&&<><p className="muted">错误编号：{errorCode}{process.env.NODE_ENV!=="production"?" · 可运行 npm run demo:doctor 查看本地自检结果":""}</p><div className="actions"><button className="button secondary" disabled={busy} onClick={()=>act(lastAction)}>重试当前操作</button><Link className="button secondary" href="/dashboard">返回我的案件</Link>{existingCaseId&&<button className="button danger" disabled={busy} onClick={()=>act("reset")}>重新创建演示案件</button>}</div></>}</div>}</details>;
}
