import { EvidenceList } from "@/components/EvidenceList";import { ExtractionReview } from "@/components/ExtractionReview";import { TimelineReview } from "@/components/TimelineReview";import { MatrixPanel } from "@/components/MatrixPanel";import { DownloadCenter } from "@/components/DownloadCenter";import { AdminPanel } from "@/components/AdminPanel";import { PlanSelector } from "@/components/PlanSelector";
import { toCaseDTO,toClaimEvidenceLinkDTO,toEvidenceFileDTO,toExtractedFieldDTO,toGeneratedDocumentDTO,toOrderDTO,toPlanDTO,toTimelineEventDTO,toUserOptionDTO } from "@/lib/dto";
import type { EvidenceRow } from "@/server/storage";import type { ExtractionRow } from "@/server/extraction";import type { TimelineRow } from "@/server/timeline";import type { MatrixRow } from "@/server/matrix";import type { GeneratedRow } from "@/server/export";import type { CaseRow } from "@/server/cases";import type { UserOption } from "@/server/backoffice";import type { OrderRow,PlanRow } from "@/server/plans";
export function EvidenceListBoundary(props:{initial:EvidenceRow[];readOnly?:boolean}){return <EvidenceList initial={props.initial.map(toEvidenceFileDTO)} readOnly={props.readOnly}/>}
export function ExtractionReviewBoundary(props:{caseId:string;initial:ExtractionRow[];readOnly?:boolean;demoTools?:boolean}){return <ExtractionReview caseId={props.caseId} initial={props.initial.map(toExtractedFieldDTO)} readOnly={props.readOnly} demoTools={props.demoTools}/>}
export function TimelineReviewBoundary(props:{caseId:string;initial:TimelineRow[];readOnly?:boolean}){return <TimelineReview caseId={props.caseId} initial={props.initial.map(toTimelineEventDTO)} readOnly={props.readOnly}/>}
export function MatrixPanelBoundary(props:{caseId:string;initial:MatrixRow[];readOnly?:boolean}){return <MatrixPanel caseId={props.caseId} initial={props.initial.map(toClaimEvidenceLinkDTO)} readOnly={props.readOnly}/>}
export function DownloadCenterBoundary(props:{caseId:string;initial:GeneratedRow[];readOnly?:boolean}){return <DownloadCenter caseId={props.caseId} initial={props.initial.map(toGeneratedDocumentDTO)} readOnly={props.readOnly}/>}
export function AdminPanelBoundary(props:{cases:CaseRow[];reviewers:UserOption[];orders:OrderRow[]}){return <AdminPanel cases={props.cases.map(toCaseDTO)} reviewers={props.reviewers.map(toUserOptionDTO)} orders={props.orders.map(toOrderDTO)}/>}
export function PlanSelectorBoundary(props:{caseId:string;plans:PlanRow[];orders:OrderRow[]}){return <PlanSelector caseId={props.caseId} plans={props.plans.map(toPlanDTO)} orders={props.orders.map(toOrderDTO)}/>}
