"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { extractionFieldLabels, fieldStateLabels } from "@/lib/labels";
import type { ExtractionRow } from "@/server/extraction";

function valueOf(raw:string|null){if(raw===null)return null;try{return JSON.parse(raw)as string|number}catch{return null}}
const confirmedStates=["CONFIRMED","MODIFIED","AI_CONFIRMED","USER_EDITED"];
export function ExtractionReview({caseId,initial,readOnly=false}:{caseId:string;initial:ExtractionRow[];readOnly?:boolean}){
  const[items,setItems]=useState(initial);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const router=useRouter();
  async function extract(){setBusy(true);setMessage("正在按文件逐项处理：图片/PDF 进入人工核对，TXT 执行结构化提取…");const response=await fetch(`/api/cases/${caseId}/extract`,{method:"POST"});const data=await response.json();setBusy(false);if(!response.ok)return setMessage(data.error?.message??"提取失败，请返回上传页检查材料后重试");setItems(data.extractions);setMessage("提取完成。材料提取值默认待确认，请逐项核对来源和数值。");}
  async function act(item:ExtractionRow,action:"CONFIRM"|"MODIFY"|"DELETE"|"UNKNOWN"){let value:string|undefined;if(action==="MODIFY"){value=prompt("请输入修正值；请只填写材料中确实存在或你能确认的内容",String(valueOf(item.originalValueJson)??""))??undefined;if(value===undefined)return;}setMessage("正在自动保存确认状态…");const response=await fetch(`/api/extractions/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,value})});const data=await response.json();if(response.ok){setItems(current=>current.map(x=>x.id===item.id?data.extraction:x));setMessage(`已保存 · ${new Date().toLocaleTimeString("zh-CN")}`);}else setMessage(data.error?.message??"保存失败，请重试");}
  async function next(){setBusy(true);const response=await fetch(`/api/cases/${caseId}/timeline`,{method:"POST"});const data=await response.json();setBusy(false);if(!response.ok)return setMessage(data.error?.message??"时间线生成失败");router.push(`/cases/${caseId}/timeline`);router.refresh();}
  return <div>{readOnly?<p className="notice">当前为人工复核只读视图，可检查来源和置信度，不能代替用户确认或重新提取。</p>:<div className="actions"><button className="button" onClick={extract} disabled={busy}>{items.length?"重新提取":"开始 Mock 提取"}</button>{items.some(x=>confirmedStates.includes(x.state))&&<button className="button secondary" onClick={next} disabled={busy}>用已确认结果生成时间线</button>}</div>}{message&&<p className="notice" aria-live="polite">{message}</p>}{!items.length?<div className="empty card"><h3>尚无提取结果</h3><p>Mock 会解析 TXT 中明确出现的字段；图片和 PDF 只标记为待人工处理。材料不齐时仍可先处理现有文件。</p></div>:<div className="review-list">{items.map(item=><article className="card review-row" key={item.id}><div><span className="status neutral">{extractionFieldLabels[item.fieldName]??item.fieldName} · {fieldStateLabels[item.state]??item.state}</span><h3>{String(valueOf(item.confirmedValueJson)??valueOf(item.originalValueJson)??"无法识别")}</h3><p className="muted">来源：{item.sourceLocator} · 置信度 {Math.round(item.confidence*100)}%</p><a className="text-link" href={`/api/evidence/${item.evidenceId}`} target="_blank">查看原始证据 ↗</a></div>{!readOnly&&<div className="compact-actions"><button onClick={()=>act(item,"CONFIRM")}>确认材料提取</button><button onClick={()=>act(item,"MODIFY")}>修改并确认</button><button onClick={()=>act(item,"UNKNOWN")}>无法确认</button><button onClick={()=>act(item,"DELETE")}>删除此项</button></div>}</article>)}</div>}</div>;
}
